apiVersion: v1
kind: Service
metadata:
  name: kubernetes-example
  labels:
    run: kubernetes-example
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
  selector:
    run: kubernetes-example